/**
 * 📄 PRIVAFLOW | Word to PDF Converter
 * ---------------------------------------------------------
 * A structural document conversion engine. Parses 
 * OpenXML (.docx) bitstreams into HTML and renders
 * a crisp PDF locally using html2pdf.js.
 * 
 * Logic: mammoth (docx -> html) -> html2pdf.js (html -> pdf)
 * Performance: O(n) Linear Conversion
 * Aesthetics: Document-Industrial / Emerald-Dark
 */

"use client";

import React, { useState, useCallback, memo, useMemo } from "react";
import { useDropzone } from "react-dropzone";
import { Loader2, FileUp, Upload, Download, CheckCircle2, Info, RefreshCw } from "lucide-react";
import { ToolContainer } from "@/components/ToolContainer";
import { useTranslations } from "next-intl";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";
import mammoth from "mammoth";
import { VisualProof } from "@/components/VisualProof";
// html2pdf is an old non-module package in some contexts, require it dynamically or use import
import html2pdf from "html2pdf.js";

/**
 * 📄 WordToPdfTool Component
 * A high-security utility for local Word to PDF conversion.
 */
const WordToPdfTool = memo(() => {
    // ✨ HOOKS & TRANSLATIONS
    const t = useTranslations("Tools.wordToPdf");
    const tc = useTranslations("Tools.common");

    // 📂 STATE ORCHESTRATION
    const [originalFile, setOriginalFile] = useState<File | null>(null);
    const [pdfBlobUrl, setPdfBlobUrl] = useState<string | null>(null);
    const [isProcessing, setIsProcessing] = useState(false);
    const [errorMsg, setErrorMsg] = useState<string | null>(null);

    /**
     * ⚡ Extraction Core
     * Parses the .docx structure, creates HTML, renders to PDF blob
     */
    const processFile = useCallback(async (file: File) => {
        setOriginalFile(file);
        setIsProcessing(true);
        setErrorMsg(null);
        setPdfBlobUrl(null);

        try {
            const arrayBuffer = await file.arrayBuffer();
            
            // Convert to HTML using mammoth with custom style mappings for better fidelity
            const options = {
                styleMap: [
                    "p[style-name='Title'] => h1.title:fresh",
                    "p[style-name='Subtitle'] => p.subtitle:fresh",
                    "p[style-name='Heading 1'] => h1:fresh",
                    "p[style-name='Heading 2'] => h2:fresh",
                    "p[style-name='Heading 3'] => h3:fresh",
                    "r[style-name='Strong'] => strong",
                    "p[style-name='Quote'] => blockquote:fresh"
                ]
            };

            const result = await mammoth.convertToHtml({ arrayBuffer }, options);
            const htmlContent = result.value;

            // Generate a container element to construct the visual layout
            const container = document.createElement("div");
            // Premium styles for PDF rendering
            container.innerHTML = `
                <style>
                    body { font-family: 'Inter', system-ui, -apple-system, sans-serif; line-height: 1.6; color: #111; padding: 0; margin: 0; }
                    .doc-container { padding: 60px 80px; background: #fff; min-height: 100vh; }
                    h1.title { font-size: 32pt; font-weight: 800; text-align: center; margin-bottom: 40px; color: #000; letter-spacing: -0.04em; }
                    h1 { font-size: 24pt; font-weight: 700; margin-top: 30px; margin-bottom: 15px; border-bottom: 1px solid #eee; padding-bottom: 10px; }
                    h2 { font-size: 18pt; font-weight: 700; margin-top: 25px; }
                    h3 { font-size: 14pt; font-weight: 700; }
                    p { font-size: 12pt; margin-bottom: 15px; text-align: justify; }
                    .subtitle { font-size: 16pt; color: #666; text-align: center; margin-top: -30px; margin-bottom: 40px; }
                    blockquote { border-left: 4px solid #ddd; padding-left: 20px; color: #555; font-style: italic; margin: 20px 0; }
                    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
                    th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
                    img { max-width: 100%; height: auto; display: block; margin: 20px auto; }
                    .footer-brand { position: absolute; bottom: 20px; left: 80px; font-size: 8px; font-weight: 800; color: #eee; text-transform: uppercase; letter-spacing: 0.1em; }
                </style>
                <div class="doc-container">
                    ${htmlContent}
                    <div class="footer-brand">Generated by PrivaFlow Offline Engine</div>
                </div>
            `;

            // Configure html2pdf options
            const opt = {
                margin:       10,
                filename:     file.name.replace(/\.docx?$/i, ".pdf"),
                image:        { type: 'jpeg' as const, quality: 0.98 },
                html2canvas:  { scale: 2 },
                jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' as const }
            };

            // Generate blob from worker
            const worker = html2pdf().set(opt).from(container);
            const pdfBlob = await worker.output('blob');
            const url = URL.createObjectURL(pdfBlob);
            
            setPdfBlobUrl(url);

        } catch (error: unknown) {
            console.error("Word to PDF error:", error);
            setErrorMsg(t('errorDesc') || "Failed to convert Word file.");
        } finally {
            setIsProcessing(false);
        }
    }, [t]);

    const onDrop = useCallback((acceptedFiles: File[]) => {
        if (acceptedFiles.length > 0) {
            processFile(acceptedFiles[0]);
        }
    }, [processFile]);

    const { getRootProps, getInputProps, isDragActive } = useDropzone({
        onDrop,
        accept: { 'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['.docx'] },
        maxFiles: 1
    });

    const handleDownload = useCallback(() => {
        if (!pdfBlobUrl || !originalFile) return;
        const link = document.createElement("a");
        link.href = pdfBlobUrl;
        const newName = originalFile.name.replace(/\.docx$/i, ".pdf");
        link.download = `privaflow_${newName}`;
        link.click();
    }, [pdfBlobUrl, originalFile]);

    const resetTool = useCallback(() => {
        setOriginalFile(null);
        setPdfBlobUrl(null);
        setErrorMsg(null);
    }, []);

    // 📦 HOW IT WORKS REGISTRY (Memoized)
    const howItWorks = useMemo(() => [
        { title: t('howItWorks.step1.title'), description: t('howItWorks.step1.desc') },
        { title: t('howItWorks.step2.title'), description: t('howItWorks.step2.desc') },
        { title: t('howItWorks.step3.title'), description: t('howItWorks.step3.desc') }
    ], [t]);

    return (
        <ToolContainer
            title={t('title')}
            description={t('description')}
            icon={FileUp}
            category="docs"
            toolId="word-to-pdf"
            settingsContent={
                <div className="space-y-4">
                    <div className="space-y-3">
                        <span className="text-[11px] font-bold uppercase tracking-widest text-zinc-500">Output Format</span>
                        <div className="border border-zinc-800 bg-zinc-950 p-3 flex items-center justify-between">
                            <span className="text-xs font-bold text-zinc-300 uppercase tracking-wide">PDF Document (.pdf)</span>
                            <RefreshCw className="w-3.5 h-3.5 text-zinc-600" />
                        </div>
                    </div>

                    <div className="space-y-3">
                        <button
                            onClick={handleDownload}
                            disabled={!pdfBlobUrl || isProcessing}
                            className="w-full h-10 bg-white hover:bg-zinc-100 disabled:opacity-40 text-black font-black rounded-sm text-xs uppercase tracking-widest flex items-center justify-center gap-2 transition-all active:scale-95"
                        >
                            {isProcessing ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
                            {isProcessing ? t('converting') : t('downloadBtn')}
                        </button>

                        <button
                            onClick={resetTool}
                            className="w-full h-10 border border-zinc-800 hover:border-zinc-600 text-zinc-500 hover:text-white text-xs font-bold uppercase tracking-widest transition-all rounded-sm"
                        >
                            <RefreshCw className="w-3.5 h-3.5 inline mr-2" />
                            {t('startOver')}
                        </button>
                    </div>

                    <div className="border border-zinc-800 bg-zinc-950 p-4 space-y-1">
                        <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-500">{t('howThisWorks')}</span>
                        <p className="text-[11px] text-zinc-600 leading-relaxed">
                            {t('howThisWorksDesc')}
                        </p>
                    </div>
                </div>
            }
            howItWorks={howItWorks}
        >
            <div className="w-full">
                <AnimatePresence mode="wait">
                    {!originalFile ? (
                        <motion.div
                            key="dropzone"
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            exit={{ opacity: 0 }}
                            className="w-full"
                        >
                            <div className="relative group/dropzone w-full">
                                <AnimatePresence>
                                    {isDragActive && (
                                        <motion.div
                                            initial={{ opacity: 0 }}
                                            animate={{ opacity: 1 }}
                                            exit={{ opacity: 0 }}
                                            className="absolute -inset-1 conic-gradient-vault animate-pulse-conic rounded-[2.7rem] blur-md -z-10"
                                        />
                                    )}
                                </AnimatePresence>
                                <div
                                    {...getRootProps()}
                                    className={cn(
                                        "w-full border border-dashed flex flex-col items-center justify-center cursor-pointer transition-all duration-200 py-10 gap-4",
                                        isDragActive ? "border-white/40 bg-white/[0.03]" : "border-zinc-800 hover:border-zinc-600 bg-zinc-950/40"
                                    )}
                                >
                                    <input {...getInputProps()} />
                                    <Upload className={cn("w-8 h-8", isDragActive ? "text-white" : "text-zinc-600")} />
                                    <div className="text-center">
                                        <p className="text-sm font-bold text-white uppercase tracking-widest">
                                            {isDragActive ? tc('dropActive') : t('dropTitle')}
                                        </p>
                                        <p className="text-xs text-zinc-600 mt-1 uppercase tracking-widest">{t('dropDesc')}</p>
                                    </div>
                                </div>
                            </div>
                        </motion.div>
                    ) : (
                        <motion.div
                            key="results"
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="w-full flex flex-col gap-4"
                        >
                            {/* Visual Proof */}
                            <VisualProof
                                toolId="word-to-pdf"
                            />

                            {/* File info row */}
                            <div className="flex items-center gap-4 p-4 border border-zinc-800 bg-zinc-950">
                                <FileUp className="w-8 h-8 text-zinc-600 shrink-0" />
                                <div className="flex-1 min-w-0">
                                    <p className="text-sm font-bold text-white truncate">{originalFile.name}</p>
                                    <p className="text-xs text-zinc-600">{(originalFile.size / 1024 / 1024).toFixed(2)} MB</p>
                                </div>
                            </div>

                            {/* State Status */}
                            <AnimatePresence>
                                {isProcessing && (
                                    <motion.div
                                        initial={{ opacity: 0 }}
                                        animate={{ opacity: 1 }}
                                        exit={{ opacity: 0 }}
                                        className="space-y-2"
                                    >
                                        <div className="flex items-center gap-2">
                                            <Loader2 className="w-4 h-4 text-white animate-spin" />
                                            <span className="text-xs font-bold uppercase tracking-widest text-zinc-400">{t('converting')}</span>
                                        </div>
                                        <div className="h-1 bg-zinc-900 overflow-hidden">
                                            <motion.div
                                                className="h-full bg-white"
                                                initial={{ width: "5%" }}
                                                animate={{ width: "95%" }}
                                                transition={{ duration: 3, repeat: Infinity, ease: "linear" }}
                                            />
                                        </div>
                                    </motion.div>
                                )}
                            </AnimatePresence>

                            {/* Error */}
                            {errorMsg && (
                                <div className="flex items-center gap-3 p-4 border border-red-500/30 bg-red-500/5 text-red-400">
                                    <Info className="w-4 h-4 shrink-0" />
                                    <p className="text-xs font-bold uppercase tracking-tight">{errorMsg}</p>
                                </div>
                            )}

                            {/* Success */}
                            {pdfBlobUrl && !isProcessing && (
                                <div className="flex items-center gap-3 p-4 border border-white/10 bg-white/[0.02] text-white">
                                    <CheckCircle2 className="w-4 h-4 shrink-0" />
                                    <p className="text-xs font-bold uppercase tracking-widest">{t('readyToDownload')}</p>
                                </div>
                            )}
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </ToolContainer>
    );
});

WordToPdfTool.displayName = 'WordToPdfTool';

export default WordToPdfTool;
